### PR TITLE
capplet: use a function to set the visibility of treeview rows

### LINKED ISSUE #260: XDG autostart enable/disable functionality not compatible with XFCE
#### Expected behaviour

.desktop files in XDG autostart locations with the key Hidden= set to true are visible in the mate-session-properties dialog and can be (re-)enabled there, other desktop envs use Hidden=true|false to enable/disable startup applications. See also #134 for how to hide startup applications from the mate-session-properties dialog entirely.

#### Actual behaviour

Currently, mate-session-properties uses a MATE specific flag for disabling XDG autostart applications (X-MATE-Autostart-enabled=false). This boolean switch is not portable to other desktop environments. Please consider using the Hidden= key instead.

The explicit problem I have is this:

  * disable autostart of an application in XFCE -> this sets Hidden=true in the .desktop file
  * I cannot re-enable autostart for this application in MATE

Other way around:

  * I disable autostart of an application in MATE -> this sets X-MATE-Autostart-enabled=false
  * the application still autostarts in XFCE

I haven't tested other desktop envs. Let me know, if I should.

The context is: Ayatana Indicators. The system indicators are services usable across different desktop envs. At some point, they should be controllable via systemd user services (on systems having systemd). On systems without systemd / as of today, XDG autostart is used to launch the system indicator services. It should be possible to enable/disable those services cross-desktop-env.

#### Steps to reproduce the behaviour

Install MATE and XFCE on the same machine. Disable/enable XDG autostarted application using mate-session-properties and XFCE's xfce4-session-settings and switch between desktop environments

#### MATE general version

1.20 / 1.24

#### Package version

1.20

#### Linux Distribution

Debian/Ubuntu

#### Link to downstream report of your Distribution

none

### PR DESCRIPTION
**Pull request by rbuj**
closes #260

### CODE REVIEW

**Comment by raveit65** [comment]
For what is this ?

**Comment by rbuj** [comment]
It improves the code comprehension and it removes unused arguments.

The `_app_added` and `_app_removed` methods are used for updating the applications listed on the treeview when there is a change in the manager. The `update_tree_view` method adds or removes the applications which are not listed by default on the treeview (see https://github.com/mate-desktop/mate-session-manager/commit/16fe21a84ea333db67e9f0509d619f8d3fee1443)

**Comment by raveit65** [comment]
Does it fix this report?
https://github.com/mate-desktop/mate-session-manager/issues/156

**Comment by rbuj** [comment]
No it isn't. It's a frontend bugfix.

#156 may be related to the backend, ie manager. I haven't reviewed it yet:
- adding or removing items in the view could call the manager
- the manager has not been implemented to handle this kind of apps (no display: introduced at 16fe21a)
- ...

File: capplet/gsm-properties-dialog.c [hunk 1]
```diff
@@ -217,6 +216,14 @@ _app_removed (GsmPropertiesDialog *dialog,
         gtk_list_store_remove (dialog->list_store, &iter);
 }
 
+static void
+_app_removed (GsmPropertiesDialog *dialog,
+              GspApp              *app,
+              GspAppManager       *manager)
```
Comment (raveit65) [inline capplet/gsm-properties-dialog.c:222]:
```
gsm-properties-dialog.c:222:36: warning: unused parameter 'manager' [-Wunused-parameter]

              GspAppManager       *manager)
```
I know `_app_removed` was there before, but now you write  the code snipset new.

Comment (rbuj) [reply capplet/gsm-properties-dialog.c:223]: Ok, I updated the pr because i think it's easier to use a function than a column for setting the visibility of the treeview rows.

**Comment by raveit65** [comment]
I tested all 3 PRs from you and my PR before you updated this PR, and the result was that the fix for https://github.com/mate-desktop/mate-session-manager/issues/156 doesn't work proper any more.
With current changes we have a conflict with my PR and one of yours.

For me the important thing is to have a proper fix for https://github.com/mate-desktop/mate-session-manager/issues/156 which was done with https://github.com/mate-desktop/mate-session-manager/pull/272

**Comment by rbuj** [comment]
#272 adds a regression as it shows all applications after launching the application because it removes update_tree_view call after calling populate_model.

**Comment by raveit65** [comment]
Mate-screensaver is always shown in dialog since the begining of MATE desktop.
This isn't wrong!

**Comment by rbuj** [comment]
@raveit65 I mean the "show hidden" checkbox.

**Comment by raveit65** [comment]
When i only use https://github.com/mate-desktop/mate-session-manager/pull/272
i can disable hidden application and i can show hidden applictions in my test.
And with both values i can disable/enable a start of an application.
I don't get what is wrong in real testing.
Don't understand me wrong....
If you really did test my PR and think this is wrong than please provide a better solution to fix https://github.com/mate-desktop/mate-session-manager/issues/156.
I am not against an improvement.

But at the moment i see only 3 new PRs but enable/disable applications in autostart isn't fixed.

**Comment by rbuj** [comment]
Try to disable `Bluetooth OBEX Agent`, which is not shown if the checkbox "show hidden" is not checked:
```
$ grep NoDisplay /etc/xdg/autostart/blueberry-obex-agent.desktop
NoDisplay=true
```
After disabling it, it should create the file below:
```
$ diff .config/autostart/blueberry-obex-agent.desktop /etc/xdg/autostart/blueberry-obex-agent.desktop
13d12
< X-MATE-Autostart-enabled=false
```
Log out/in, check blueberry-obex-agent:
```
$ grep Exec /etc/xdg/autostart/blueberry-obex-agent.desktop
Exec=/usr/lib/blueberry/blueberry-obex-agent.py
$ ps ax | grep blueberry-obex-agent
```

**Comment by rbuj** [comment]
Ok, I think the bug you're referring to is that it doesn't save the change after you clicked the the checkbox, and it's only saved if when you clicked on another item of list.

**Comment by rbuj** [comment]
`on_startup_enabled_toggled` is working properly.

**Comment by raveit65** [comment]
The bug is that enable/disable a service in main GUI doesn't change the settings, a workaround is to open the preferences of `a service` and save the status of a service there.
The issue only exists if `enable-hidden` checkbox is checked.
Described here:
https://github.com/mate-desktop/mate-session-manager/issues/156#issuecomment-808731386
https://github.com/mate-desktop/mate-session-manager/issues/156#issuecomment-808893461

**Comment by raveit65** [comment]
> and it's only saved when you clicked on another item of list.

Looks like you found another workaround :)

**Comment by rbuj** [comment]
> > and it's only saved when you clicked on another item of list.
> 
> Looks like you found another workaround :)

It's because of GSP_APP_SAVE_DELAY. There is a delay of two second before saving the file.

Anyway the files are generated in `$HOME/.config/autostart` folder when there is no difference with the original file, and they are deleted otherwise.

File: capplet/gsm-properties-dialog.c (hunk 1 above)
Comment (raveit65) [reply capplet/gsm-properties-dialog.c:218]: The warning is still there.
https://travis-ci.org/github/mate-desktop/mate-session-manager/jobs/767534724#L2537
```
gsm-properties-dialog.c:218:36: warning: unused parameter 'manager' [-Wunused-parameter]

              GspAppManager       *manager)
```

**Comment by raveit65** [comment]
I can confirm that this PR fixes https://github.com/mate-desktop/mate-session-manager/issues/156 and other open variants of the same issue. Thank you
Which part fixes enable/start services?
We need to fix the issue for 1.24 branch too.

File: capplet/gsm-properties-dialog.c (hunk 1 above)
Comment (rbuj) [reply capplet/gsm-properties-dialog.c:219]: done

Comment (raveit65) [reply capplet/gsm-properties-dialog.c:219]: Thx

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@rbuj 
Simply cherry-picking doesn't work for stable branch.
Can this be done for 1.24 branch, please?

**Comment by rbuj** [comment]
ok, wip

**Comment by rbuj** [comment]
PR #279
